### ISSUE TITLE
tab height 

### ISSUE THREAD

**Issue by lambster** [edelvarden/material-fox-updated#1]
could you make the tab height the same as chrome as it was before I noticed the tabs are a lot smaller than before

**Comment by edelvarden** [comment]
> could you make the tab height the same as chrome as it was before I noticed the tabs are a lot smaller than before

Hi, default chrome tab height is 34px, You can find --tab-min-height in user-chrome.css and change 34 to your custom value.

**Comment by lambster** [comment]
hi thanks for the reply sorry im a noob with ccs i only really know how to instail it i cant find the  --tab-min-height https://i.imgur.com/ar3KeJB.png

**Comment by edelvarden** [comment]
> hi thanks for the reply sorry im a noob with ccs i only really know how to instail it i cant find the --tab-min-height https://i.imgur.com/ar3KeJB.png

Yea, it might be little tricky in my project because i use minify css for output code, but I hope my screenshot will help you.
![Screenshot 2022-11-12 222307](https://user-images.githubusercontent.com/42596339/201493357-2870ec26-f3a1-4bf6-b004-f039fef4d508.png)

**Comment by lambster** [comment]
okay ive found it thamkyou! youre theme is by far the best ive seen

**Comment by edelvarden** [comment]
> okay ive found it thamkyou! youre theme is by far the best ive seen

Glad I could help.
