### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Crunchbits** [edelvarden/material-fox-updated#10]
### Description

When having more than 1 pinned tab and more tabs than would fit horizontally on the Firefox window (when tab's width start to get smaller), the pinned tab icons get weirdly clipped/ cut out.

2 pinned tabs + 7 tabs:
![Screenshot_7](https://user-images.githubusercontent.com/87384615/236067856-4ee0754a-2b35-4ae4-8387-0bd54cab5549.png)

2 pinned tabs + 8 tabs:
![Screenshot_8](https://user-images.githubusercontent.com/87384615/236067869-e1f182cd-6ec7-4dae-b502-026bb58d8994.png)

I could be wrong but it looks like it's a titlebar-spacer being created. I don't know if that's it but no idea how to fix.

### Additional info

Windows 10
Firefox 112.0.2 (64-bit)

**Comment by edelvarden** [comment]
added fixes
