### ISSUE TITLE
[Bug]: Extension's detail buttons are hidden in about:addons page

### ISSUE THREAD

**Issue by Crunchbits** [edelvarden/material-fox-updated#11]
### Description

For whatever reason on extensions the text for these are hidden:
![Screenshot_11](https://user-images.githubusercontent.com/87384615/236339869-aea18de3-6866-477f-896a-236a5e9b2f09.png)

I was able to fix it by going to the user-content.css and ~Line 111 and removing the 'button,' line from:
```
input,
button,
textarea,
select {
    font: inherit !important;
    letter-spacing: inherit !important;
    word-spacing: inherit !important
}
```
This is how it looks afterwards:
![Screenshot_12](https://user-images.githubusercontent.com/87384615/236339889-84ce5853-8620-4999-9acc-b6b28948bd00.png)

So it seems to fix it but I'm not sure if doing that will cause unwanted effects.  Could be a full fix or maybe not, not sure.

### Additional info

Windows 10
Firefox 112.0.2 (64-bit)

**Comment by edelvarden** [comment]
Ok, thanks for solution, how I tested the problem in "font" property. As an alternative you can replace to ":not(button-group) > button" but I comment "button", this is not critical.
