### ISSUE TITLE
[Bug]: Wired context menu color and no hover effects

### ISSUE THREAD

**Issue by PH-68** [edelvarden/material-fox-updated#12]
### Description

material-fox-updated:

<img width="172" alt="image" src="https://github.com/edelvarden/material-fox-updated/assets/58099156/6e191644-65f2-4129-a45e-1e315c1cb8c1">

chrome:

<img width="223" alt="image" src="https://github.com/edelvarden/material-fox-updated/assets/58099156/9eac025a-140c-4be0-a0fd-575c78cad9ed">

### Additional info

LibreWolf Version 114.0.2-1

Windows 11

**Comment by edelvarden** [comment]
Added fixes.
