### ISSUE TITLE
Support for custom colour schemes

### ISSUE THREAD

**Issue by IdkWhatToCallMe123** [edelvarden/material-fox-updated#14]
### Description

Is this possible to implement in some convenient way?

Thx in advance

**Comment by edelvarden** [comment]
If you are familiar with programming, you can create a custom preset, for example:
1. Create color preset in `src/variables/_colors.scss`
```scss
...
$theme-name: (
  "accent-color": #2f81f7,
  "background-color-0": #0d1117,
  "background-color-50": #161b22,
  "background-color-100": #21262d,
  "menu-border-color": #30363d,
  // add other variables you want to change
);
...
```
2. For loading with parameter add this code in `src/variables/_index.scss`
```scss
...
@supports -moz-bool-pref("userChrome.theme-name") {
  @each $key, $value in $theme-name {
    --#{$prefix}-#{$key}: #{$value};
  }
}
...
```

Where `userChrome.theme-name` this is parameter name for `about:config`

3. Replace `theme-name` to your name.

It is possible to create custom color presets, but anyway, I don't know what you mean by "convenient" way, maybe you can provide some examples or tell more about what you mean.

**Comment by IdkWhatToCallMe123** [comment]
I mean so i can use something like Firefox colour. The old materialfox theme applied the Chrome colours via a Firefox colour theme, which meant that I could just install what ever other clour theme i liked.

**Comment by edelvarden** [comment]
> I mean so i can use something like Firefox colour. The old materialfox theme applied the Chrome colours via a Firefox colour theme, which meant that I could just install what ever other clour theme i liked.

Ok, I see what you mean, I also already tested it in old materialfox, but not all firefox color themes are 100% supported, this means that may make visual bugs and unwanted results. 

This is hard to implement for current version because I add many fixes for default styles and colors to make it more consistent.

But anyway, you can suggest create a color theme special for you, just provide info about your preferences, include screenshots or any source links to help me better understand what you want.

**Comment by IdkWhatToCallMe123** [comment]
The colour scheme I wanted was the Catppuccin I wanted.
Though if you could implement some way to just use the Firefox theme colours you could make it work with [this](https://github.com/easonwong-de/Adaptive-Tab-Bar-Colour) which would be pretty cool

**Comment by edelvarden** [comment]
> The colour scheme I wanted was the Catppuccin I wanted. Though if you could implement some way to just use the Firefox theme colours you could make it work with [this](https://github.com/easonwong-de/Adaptive-Tab-Bar-Colour) which would be pretty cool

I tried to implement "Adaptive Tab Bar Color" support, updated archive on [release](https://github.com/edelvarden/material-fox-updated/releases/latest) page, this is also can support other firefox themes.

To enable it just go to  `about:config` and add `userChrome.default-theme-colors`

But right now this is experimental, and that may make visual bugs and unwanted results.

**Comment by edelvarden** [comment]
Yeah, "Adaptive Tab Bar Color" looks good, github page looks similar as my custom variant. 

Some screenshots:
![image](https://github.com/edelvarden/material-fox-updated/assets/42596339/5316dcd3-7691-4cdc-97b8-8c46bbf4737f)
![image](https://github.com/edelvarden/material-fox-updated/assets/42596339/735ca5e6-7316-4a2c-90fa-4008c85020bd)
