### ISSUE TITLE
[Bug]: Linux - Misaligned text in right click context menu

### ISSUE THREAD

**Issue by xfzv** [edelvarden/material-fox-updated#17]
### Description

Not sure if Linux is supported as there's no mention of it in the README.
Everything looks fine I guess, except the right click context menus (misaligned text):

![image](https://github.com/edelvarden/material-fox-updated/assets/78810647/836dbe51-4b08-4178-a6e5-1c3f537ba9b7)

![image](https://github.com/edelvarden/material-fox-updated/assets/78810647/ff7f029b-6a37-4e87-b5f4-c13ca6ae3857)

Content of my `chrome` directory:

```console
.
├── fonts
│   ├── Roboto-Bold.woff2
│   ├── Roboto-Medium.woff2
│   ├── Roboto-Regular.woff2
│   └── index.css
├── icons
│   ├── arrow-back.svg
│   ├── audio-blocked.svg
│   ├── audio-muted.svg
│   ├── audio.svg
│   ├── check.svg
│   ├── chevron.svg
│   ├── circle-dark.svg
│   ├── circle.svg
│   ├── close-tab.svg
│   ├── close.svg
│   ├── edit.svg
│   ├── extension.svg
│   ├── folder.svg
│   ├── home.svg
│   ├── info.svg
│   ├── lock.svg
│   ├── menu-update.svg
│   ├── menu.svg
│   ├── new-tab.svg
│   ├── no-src.svg
│   ├── properties.svg
│   ├── refresh.svg
│   ├── settings.svg
│   ├── spinner-busy.svg
│   ├── spinner-progress.svg
│   ├── star.svg
│   ├── tracking-protection.svg
│   └── warning.svg
├── user-chrome.css
├── user-content.css
├── userChrome.css
└── userContent.css

3 directories, 36 files
```

### Additional info

- Distro: Gentoo
- Firefox version: 117.0.1
- material-fox-updated version: v1.0.3 | Firefox 117

**Comment by edelvarden** [comment]
Added fixes, you can reinstall archive from release page.

Linux can be supported, but anyway it may have bugs, because there is no proper testing.

P.S. Big respect for Gentoo users.

**Comment by xfzv** [comment]
Thanks, all good now!
