### ISSUE TITLE
[Bug]: "open Link" in other App  prompt (Like Spotify ore torrent) not working

### ISSUE THREAD

**Issue by Gammelstulle** [edelvarden/material-fox-updated#18]
### Description

Hi,

If Material Fox is installed and I try to open a link for another application, the prompt does not allow me to open it. The button is even grayed out under Linux.
Under windows, the "open link" button looks kind of broken and also not work.
![grafik](https://github.com/edelvarden/material-fox-updated/assets/21155790/8c0e9015-b8d1-4b40-b10e-f27f41c697bf)

- I tryed the troubleshoot mode -> open a link for another application works just fine
-  I deactivate all my addons to be to be sure that a ddon isntead messing with the prombt
-  I tested it also in firefox instead of waterfox, same result. 

### Additional info

Application Basics
------------------

Name: Waterfox
Version: G6.0.2
Build ID: 20231004064944
Distribution ID: hawkeye116477
User Agent: Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0
OS: Linux 6.5.5-x64v3-xanmod1 #0~20230923.gb10e545 SMP PREEMPT_DYNAMIC Sat Sep 23 15:52:33 UTC
OS Theme: Pop-dark / Pop
Multiprocess Windows: 3/3
Fission Windows: 3/3 Enabled by default
Remote Processes: 28
Enterprise Policies: Inactive
Google Location Service Key: Missing
Google Safebrowsing Key: Missing
Mozilla Location Service Key: Missing
Safe Mode: false
Memory Size (RAM): 15,2 GB
Disk Space Available: 301 GB

Waterfox Features
-----------------

Name: Firefox Screenshots
Version: 39.0.1
ID: screenshots@mozilla.org

Name: Form Autofill
Version: 1.0.1
ID: formautofill@mozilla.org

Name: Picture-In-Picture
Version: 1.0.0
ID: pictureinpicture@mozilla.org

Name: Web Compatibility Interventions
Version: 115.1.0
ID: webcompat@mozilla.org

Name: WebCompat Reporter
Version: 1.5.1
ID: webcompat-reporter@mozilla.org

Remote Processes
----------------

Type: Isolated Web Content
Count: 21

Type: RDD
Count: 1

Type: Isolated Service Worker
Count: 2

Type: Privileged About
Count: 1

Type: Sandboxed IPC Actor
Count: 1

Type: Extension
Count: 1

Type: Socket
Count: 1

Add-ons
-------

Name: 'Improve YouTube!' 🎧 (for YouTube & Videos)
Type: extension
Version: 4.350
Enabled: true
ID: {3c6bf0cc-3ae2-42fb-9993-0d33104fdcaf}

Name: Ad Blocker for Facebook™
Type: extension
Version: 1.9.14
Enabled: true
ID: {d403ee9c-3bd2-41d3-b1e9-27698babf097}

Name: AdBlocker for YouTube™
Type: extension
Version: 0.3.7
Enabled: true
ID: jid1-q4sG8pYhq8KGHs@jetpack

Name: Add-ons Search Detection
Type: extension
Version: 2.0.0
Enabled: true
ID: addons-search-detection@mozilla.com

Name: Addon Store Compatibility
Type: extension
Version: 1.0.0
Enabled: true
ID: addonstores@waterfox.net

Name: Bing
Type: extension
Version: 1.3
Enabled: true
ID: bing@search.waterfox.net

Name: Dark Reader
Type: extension
Version: 4.9.67
Enabled: true
ID: addon@darkreader.org

Name: DuckDuckGo
Type: extension
Version: 1.1
Enabled: true
ID: ddg@search.waterfox.net

Name: Ecosia
Type: extension
Version: 1.1
Enabled: true
ID: ecosia@search.waterfox.net

Name: FrankerFaceZ
Type: extension
Version: 4.0
Enabled: true
ID: frankerfacez@frankerfacez.com

Name: Google
Type: extension
Version: 1.2
Enabled: true
ID: google@search.waterfox.net

Name: I don't care about cookies
Type: extension
Version: 3.4.9
Enabled: true
ID: jid1-KKzOGWgsW3Ao4Q@jetpack

Name: Keepa - Amazon Price Tracker
Type: extension
Version: 4.10
Enabled: true
ID: amptra@keepa.com

Name: Qwant
Type: extension
Version: 1.1
Enabled: true
ID: qwant@search.waterfox.net

Name: Return YouTube Dislike
Type: extension
Version: 3.0.0.10
Enabled: true
ID: {762f9885-5a13-4abd-9c77-433dcd38b8fd}

Name: SoundCloud Downloader
Type: extension
Version: 1.13.2
Enabled: true
ID: {c7a839e7-7086-4021-8176-1cfcb7f169ce}

Name: SponsorBlock für YouTube - Überspringe gesponserte Videosegmente
Type: extension
Version: 5.4.22
Enabled: true
ID: sponsorBlocker@ajay.app

Name: Startpage
Type: extension
Version: 1.0
Enabled: true
ID: startpage@search.waterfox.net

Name: Tampermonkey
Type: extension
Version: 4.19.0
Enabled: true
ID: firefox@tampermonkey.net

Name: TTV LOL PRO
Type: extension
Version: 2.1.6
Enabled: true
ID: {76ef94a4-e3d0-4c6f-961a-d38a429a332b}

Name: Yahoo!
Type: extension
Version: 1.0
Enabled: true
ID: yahoo@search.waterfox.net

Name: Language: Deutsch (German)
Type: locale
Version: 115.4.0
Enabled: true
ID: langpack-de@l10n.waterfox.net

Name: Grammatik- und Rechtschreibprüfung – LanguageTool
Type: extension
Version: 7.1.13
Enabled: false
ID: languagetool-webextension@languagetool.org

Name: uBlock Origin
Type: extension
Version: 1.52.2
Enabled: false
ID: uBlock0@raymondhill.net

**Comment by edelvarden** [comment]
Are you sure this is a user css issue? It is not possible to disable or enable buttons using css, css only changes the colors and appearance.

Troubleshoot mode disabled all your user settings not only user css. 

If you are 100% sure that this is a custom css issue, I provide some suggestion:
1. Go to `about:config` and set `toolkit.legacyUserProfileCustomizations.stylesheets` to `false`. 
2. Restart Firefox and try to open your link, if it doesn't work then it's not a custom css problem.

If after prev steps your link works tell me about it.

**Comment by edelvarden** [comment]
Added fixes

**Comment by Gammelstulle** [comment]
the issue is, looks like waterfox not let me change the option to false. 😅
I will test it at home again with the regular firefox version.

What I tested  instead was to remove the chrome  theme folder from my profile and let anythink else untouched (so all my addons and so on active) and open links worked again :< .
But if it makes no sense for you as explained above... I'm lost with ideas 😅

Edit: Working now !! thx dude for the quick fix  :3
