### ISSUE TITLE
[Bug]: MacOS Sonoma 14.0 settings menu popup doesn't display properly

### ISSUE THREAD

**Issue by finnmerlett** [edelvarden/material-fox-updated#19]
### What happened?

Menu doesn't display properly, appears to be hidden or 1px width

![Screenshot 2023-10-18 at 10 05 27](https://github.com/edelvarden/material-fox-updated/assets/49064567/c4fda32a-7eb8-47f0-9f7e-e4511f9e6836)

### Steps to reproduce the problem

1. Extract theme zip to /Users/\<user\>/Library/Application Support/Firefox/Profiles/\<profile-code\>.default-release/chrome
2. Open Firefox
3. Observe theme has activated
4. Click three dot menu
5. Observe menu is super thin (see screenshot)

### Additional info (Optional)

Firefox version: 118.0.2 (64-bit)
Operating system: MacOS Sonoma 14.0

**Comment by finnmerlett** [comment]
Actually almost all of the popup menus are either 1px or too thin

**Comment by edelvarden** [comment]
Added fixes, reinstall archive please.

**Comment by finnmerlett** [comment]
Omg you absolute legend, perfect fix. MAN I love this theme, thanks so much!

**Comment by finnmerlett** [comment]
![Screenshot 2023-10-19 at 11 04 08](https://github.com/edelvarden/material-fox-updated/assets/49064567/ae6319dc-fa9e-48a7-a21e-585ba9f9c417)
One final tweak (don't know how much of a perfectionist you are) is on hover an inactive tab appears faintly on top of the active tab in the corner. should be a simple z-index fix. Didn't want to make a whole new issue just for that tho

**Comment by edelvarden** [comment]
> ![Screenshot 2023-10-19 at 11 04 08](https://user-images.githubusercontent.com/49064567/276571937-ae6319dc-fa9e-48a7-a21e-585ba9f9c417.png) One final tweak (don't know how much of a perfectionist you are) is on hover an inactive tab appears faintly on top of the active tab in the corner. should be a simple z-index fix. Didn't want to make a whole new issue just for that tho

Ok, ill try fix this as soon as possible.
