### ISSUE TITLE
ccs broken after firefox 108.1

### ISSUE THREAD

**Issue by lambster** [edelvarden/material-fox-updated#2]
hey after ff 108.1 seemed to have broken the visuals https://i.imgur.com/K9tV7fI.png

**Comment by edelvarden** [comment]
> hey after ff 108.1 seemed to have broken the visuals https://i.imgur.com/K9tV7fI.png

It's too late, but I want to wish you a Happy New Year. I fixed some things which I seen. So you can try reinstall and check, if I missed something, then write more specifically what I need to fix.

**Comment by lambster** [comment]
ill have to get used to the audio icon to be hidden until i hover over it now lol but it's fixed now thankyou so much and happy new year to you too :)

**Comment by edelvarden** [comment]
> ill have to get used to the audio icon to be hidden until i hover over it now lol but it's fixed now thankyou so much and happy new year to you too :)

Yes, I restored the standard firefox behavior, new firefox version broke my custom styles for that, maybe I rewrite it later.

**Comment by lambster** [comment]
ohh okay i see well thankyou for fixing it

**Comment by edelvarden** [comment]
> ohh okay i see well thankyou for fixing it

Ok, enjoy ;)
