### ISSUE TITLE
[Bug]: theme

### ISSUE THREAD

**Issue by BrashShepherd** [edelvarden/material-fox-updated#20]
### What happened?

The chrome theme works very well. It is my favorite themes for firefox, but there is one thing. For the firefox themes with the userChrome.default-theme-colors thing in about:config. When i try to use a theme, the bookmarks bar and search bar change, but the tabs don't.

### Steps to reproduce the problem

turn on userChrome.default-theme-colors in about:config
turn on theme of choice

### Additional info (Optional)

Firefox version: 118.0.2
Operating system: macos 12

**Comment by edelvarden** [comment]
Reinstall zip please, I improved compatibility for this feature
