### ISSUE TITLE
[Bug]: Custom tab background colour is no longer set correctly in Firefox 119 (stable)

### ISSUE THREAD

**Issue by Crunchbits** [edelvarden/material-fox-updated#22]
### What happened?

Tab background colour(inactive tabs + general tab background) changed from material-fox-updated's #202124 to #1c1b22.

Found a somewhat related [reddit post](https://www.reddit.com/r/FirefoxCSS/comments/17eoyyo/the_custom_tab_background_colour_is_no_longer_set/) but couldn't figure out a fix for material-fox-updated.

### Steps to reproduce the problem

Update to Firefox 119 (stable)

### Additional info (Optional)

Firefox version: 119.0 (64-bit)
Operating system: Windows 10

**Comment by edelvarden** [comment]
Created new release with fixes, try to reinstall please. As I tested this is actual only with Firefox auto color scheme.
