### ISSUE TITLE
Best Settings Guide to Exactly Mimic Google Chrome

### ISSUE THREAD

**Issue by PeteBaker1** [edelvarden/material-fox-updated#25]
### Description

Hi, I noticed that on the search bar for example that the font for firefox is different from the chrome font and same with a few other colours, like when on the active tab on firefox, it has a light blue hue but on chrome it just has a light grey hue. Is it possible to release a guide for how to configure firefox/this add on so it closely matches chrome, thanks :)

### Additional info (Optional)

Firefox version: 119
Operating system: Windows 11

**Comment by edelvarden** [comment]
You can try change values for:

```css
--mf-text-primary
```

Also I described how change font, please check readme for that.
