### ISSUE TITLE
[Bug]: autoscroller is too wide

### ISSUE THREAD

**Issue by notpeelz** [edelvarden/material-fox-updated#26]
### What happened?

Expected:
![image](https://github.com/edelvarden/material-fox-updated/assets/920910/b32a3881-05c2-4b7d-8367-715031975f84)

Actual:
![image](https://github.com/edelvarden/material-fox-updated/assets/920910/b2aa9adf-eed0-4ec6-b4ce-9b228e64980f)

### Steps to reproduce the problem

1. enable `general.autoScroll`
2. middle click (on a scrollable page)
3. observe the wide autoscroller

### Additional info

Firefox version: 119.0
Operating system: Arch Linux (x86-64)

### Workaround

I couldn't figure out what rule(s) affect the autoscroller like that, but in the meantime I'm using this to restore the width:
```css
.autoscroller {
  min-width: 0 !important;
}
```

**Comment by edelvarden** [comment]
Added fix, reinstall archive please.

**Comment by notpeelz** [comment]
I use a git clone of the repo with a custom patchset, but thanks nonetheless. Maybe it would be appropriate to have multiple branches for backporting fixes to older versions of Firefox (or maybe just branches for the current and next versions)?

**Comment by edelvarden** [comment]
I'll think about it, because there are quite serious changes in version 120, and it make a sense to separate in another branch
