### ISSUE TITLE
[Feature Request]: Adjustable shortcut size

### ISSUE THREAD

**Issue by quarkquartet** [edelvarden/material-fox-updated#28]
### Description

First, thank you for your great work. This is truly an amazing job.

One small suggestion is that the shortcut on the homepage becomes rounded and small. I know chrome behaves like this but it maybe too small for me. (It's both OK for round or not, just about the size). It could be very nice if the size of the shortcut is adjustable.

### Additional info (Optional)

Firefox version: 120.0
Operating system: MacOS 14.

**Comment by quarkquartet** [comment]
Update by myself:
The current way is to modify the `icon-wrap` quantity. Just search this variable through this project. There are just 2 appearances and they are close to each other. Modify the corresponding width and height and that's it.

**Comment by edelvarden** [comment]
Sorry that I did not reply for a while, you can use custom css for your needs:

```css
.tile .icon-wrapper {
  width: 100% !important;
  height: 100% !important;
}
```

It makes icons bigger, you can also change `100%` with your own value in px. If I don't clearly understand what you want describe more.

**Comment by quarkquartet** [comment]
> Sorry that I did not reply for a while, you can use custom css for your needs:
> 
> ```css
> .tile .icon-wrapper {
>   width: 100% !important;
>   height: 100% !important;
> }
> ```
> 
> It makes icons bigger, you can also change `100%` with your own value in px. If I don't clearly understand what you want describe more.

Thank you. I think this could be helpful enough. I was originally expecting some quick variable in about:config could be the best, but it seems that customizing CSS could be easy enough.
