### ISSUE TITLE
[Bug]: Containers have no colour in tab menu

### ISSUE THREAD

**Issue by bbhtt** [edelvarden/material-fox-updated#31]
### What happened?

Containers have no colour, they look grey with the default setup. While the tab context menu > Open tab in New container preserves the colours.

### Steps to reproduce the problem

1. Install Multi account container extension
2. Click the tab menu
3. See that they have no colour, only the icon is preserved.

![image](https://github.com/edelvarden/material-fox-updated/assets/62639087/1b369aee-5139-493d-b615-c41240c7493f)

### Additional info (Optional)

Firefox version: 119
Operating system: Fedora 39

**Comment by bbhtt** [comment]
Looks like on Nightly that tab menu is now placed on the left corner with the theme instead of right like in 119.

**Comment by edelvarden** [comment]
Added fixes, can you test again please. Also the difference between Firefox 119 and 120 is quite serious, I separated it in another branch if you want to use in older versions.

**Comment by bbhtt** [comment]
Thanks! It works now

![image](https://github.com/edelvarden/material-fox-updated/assets/62639087/4cf954e6-016f-4e1a-a216-3c8bcce4bde1)
