### ISSUE TITLE
[Bug]: Pinned tab playing media hides favicon

### ISSUE THREAD

**Issue by bbhtt** [edelvarden/material-fox-updated#32]
### What happened?

Probably the pinned state has too low width or should be visible on hover.

[a1f2de23fc.webm](https://github.com/edelvarden/material-fox-updated/assets/62639087/26b6b458-4d00-4d8c-8500-5ca6764ac6b7)

### Steps to reproduce the problem

1. Play music on tab
2. Pin it
3. See that site favicon is hideen

### Additional info (Optional)

Use chrome referesh 2023

Firefox version: Nightly
Operating system: Fedora 39

**Comment by edelvarden** [comment]
This is not bug, this is feature, chrome have the same behavior.
