### ISSUE TITLE
[Bug]: Icon alignment in bookmarks bar

### ISSUE THREAD

**Issue by mclarenf1lm15** [edelvarden/material-fox-updated#33]
### What happened?

I know this is incredibly minor, but at least for me, the icons in the bookmark bar are a couple of pixels further down than the text. 

In Firefox:
![firefox](https://github.com/edelvarden/material-fox-updated/assets/31804696/3c501bb0-996d-45f8-9a42-d86d553e166b)

In Chrome:
![chrome](https://github.com/edelvarden/material-fox-updated/assets/31804696/a2476a89-3a4c-402d-ac42-cfb616e78657)

### Additional info (Optional)

Firefox version: 120
Operating system: Windows 11

**Comment by edelvarden** [comment]
Don't worry about is this minor or not, because I can miss something.

Added fixes and implemented new style for bookmarks bar, can you test again please.

**Comment by mclarenf1lm15** [comment]
Unfortunately it didn't seem to change anything.  

Although (and I by no means have any coding knowledge) when I changed this 
#nav-bar #stop-button .toolbarbutton-icon{padding:4px !important}

to 
#nav-bar #stop-button .toolbarbutton-icon{padding:30px !important}

It went from:
![Screenshot 2023-11-28 203857](https://github.com/edelvarden/material-fox-updated/assets/31804696/dd731363-f318-4fb0-bac6-9a2812a30452)


to

![Screenshot 2023-11-28 203635](https://github.com/edelvarden/material-fox-updated/assets/31804696/9719fa8f-2f17-462a-8791-91b9735d7688)


Slight difference, but the text and icons seemed to align but obviously the other parts were thicker.

**Comment by edelvarden** [comment]
I can't reproduce your issue, in my case its looks like 
![image](https://github.com/edelvarden/material-fox-updated/assets/42596339/0d371646-d938-43ea-b3dc-9aa84c0d7a3a)
Where the first is in Chrome and the second is in Firefox, both have the same position and sizes.

As a solution I can suggest you to use the following selector instead of yours

```css
#PlacesToolbarItems > .bookmark-item > label {
 transform: translateY(2px) !important;
}
```

Change `2px` to your own value, but I think value 1 or 2 can solve your isssue.

**Comment by mclarenf1lm15** [comment]
1px worked for me. Thank you!
