### ISSUE TITLE
[Bug]: can't seem to disable "chrome refresh 2023"

### ISSUE THREAD

**Issue by shiypc** [edelvarden/material-fox-updated#35]
### What happened?

the "chrome refresh 2023" appearance seems to be always on even if disabled in about:config
<img width="413" alt="Screen Shot 2023-12-01 at 1 12 35 PM" src="https://github.com/edelvarden/material-fox-updated/assets/26725277/76ce8843-e37b-49ed-9dba-55575c4d2b30">
<img width="1470" alt="Screen Shot 2023-12-01 at 1 13 24 PM" src="https://github.com/edelvarden/material-fox-updated/assets/26725277/42b78953-50ef-4aba-8eda-bb20e3bf8e56">

### Steps to reproduce the problem

1. install theme manually on macOS
2. add a config key to about:config titled `userChrome.chrome-refresh-2023` and set it to `false`
3. restart firefox from about:profiles, no changes occur

### Additional info (Optional)

Firefox version: 120.0.1
Operating system: macOS Monterey 12.5 21G72

**Comment by shiypc** [comment]
update: setting `userChrome.chrome-refresh-colors` to false does not do anything either

**Comment by edelvarden** [comment]
`userChrome.chrome-refresh-colors` only updates dark mode colors, since by default it uses new colors for the light mode, and it don't do anything because it inherits the light/dark mode from your system, if you set dark mode you can see changes.

**Comment by edelvarden** [comment]
If you want always see the dark mode, change Firefox color mode from auto to dark.

**Comment by shiypc** [comment]
> If you want always see the dark mode, change Firefox color mode from auto to dark.

sorry for late response, but i'm talking about the blue tint in the title bar which is not present in old chrome versions
