### ISSUE TITLE
[Bug]: visual error on the first tab with Chrome Refresh 2023

### ISSUE THREAD

**Issue by Noi42** [edelvarden/material-fox-updated#36]
### What happened?

When `userChrome.chrome-refresh-2023` is turned on, the first tab looks like this:
![изображение](https://github.com/edelvarden/material-fox-updated/assets/66965791/7faca4bc-565d-4a79-b680-eac49e6267bd) ![изображение](https://github.com/edelvarden/material-fox-updated/assets/66965791/a57d6b42-aa99-4ff5-afef-05a4d94bd937)

### Steps to reproduce the problem

1. Enable `userChrome.chrome-refresh-2023`

### Additional info (Optional)

Firefox version: 121.0b9 (Developer Edition), also tested on a stable 120.0.1
Operating system: Arch linux
material-fox-updated version: Latest commit from github ([7a5685a](https://github.com/edelvarden/material-fox-updated/commit/7a5685adf41f28c1252bf2c63e3edee62be29cc6))

**Comment by edelvarden** [comment]
Added fix
