### ISSUE TITLE
Make Pinned tabs  look like regular tabs

### ISSUE THREAD

**Issue by swarupsesha** [edelvarden/material-fox-updated#37]
### Description

Is it possible to make the pinned tabs look and feel like regular tabs? I have this piece of code here https://github.com/MrOtherGuy/firefox-csshacks/blob/master/chrome/normal_pinned_tabs.css but not sure where to make the changes in the current user-chrome file.

### Additional info (Optional)

Firefox version: 
Operating system:

**Comment by edelvarden** [comment]
> ### Description
> Is it possible to make the pinned tabs look and feel like regular tabs? I have this piece of code here https://github.com/MrOtherGuy/firefox-csshacks/blob/master/chrome/normal_pinned_tabs.css but not sure where to make the changes in the current user-chrome file.
> 
> ### Additional info (Optional)
> Firefox version: Operating system:

I think you should adapt your css, user-chrome file is hard to manually changing, `custom.css` file implemented for this needs. 

[How to add user CSS](https://github.com/edelvarden/material-fox-updated/tree/main?tab=readme-ov-file#custom-css-rules)
