### ISSUE TITLE
[Bug]: opening 20 tabs bring scrolling behavior as opposed to minimizing tab

### ISSUE THREAD

**Issue by ghost** [edelvarden/material-fox-updated#42]
### What happened?

<img width="1680" alt="Screenshot 2024-02-25 at 5 48 20 PM" src="https://github.com/edelvarden/material-fox-updated/assets/155139404/7fecb7ef-4570-4b77-85d5-b1d7d387410a">
When I open 20+ tabs, instead of minimizing the tabs to be as little as possible like Chrome, it brings the scrolling behavior. How to fix??

### Steps to reproduce the problem

1. Open 20+ tabs
2. Scrolling behavior will happen as opposed to minimize tab width to be as low as possible

### Additional info (Optional)

Firefox version: 123
Operating system: MacOS Sonoma

**Comment by edelvarden** [comment]
I think this is impossible using only css.

**Comment by ghost** [comment]
> I think this is impossible using only css.

Could you make a patch to make it work with JS? I wouldn't mind adding Js code to the file

**Comment by edelvarden** [comment]
> > I think this is impossible using only css.
> 
> Could you make a patch to make it work with JS? I wouldn't mind adding Js code to the file

Sorry, can't do this

**Comment by ghost** [comment]
> > > I think this is impossible using only css.
> > 
> > 
> > Could you make a patch to make it work with JS? I wouldn't mind adding Js code to the file
> 
> Sorry, can't do this

No worries. I'll leave this issue open if anyone wants to make a patch for it, but feel free to close it if you want.

**Comment by edelvarden** [comment]
> > > > I think this is impossible using only css.
> > > 
> > > 
> > > Could you make a patch to make it work with JS? I wouldn't mind adding Js code to the file
> > 
> > 
> > Sorry, can't do this
> 
> No worries. I'll leave this issue open if anyone wants to make a patch for it, but feel free to close it if you want.

I found a solution, try this

```css
.tabbrowser-tab {min-width: initial !important;}
.tab-content {overflow: hidden !important;}
```

**Comment by ghost** [comment]
> > > > > I think this is impossible using only css.
> > > > 
> > > > 
> > > > Could you make a patch to make it work with JS? I wouldn't mind adding Js code to the file
> > > 
> > > 
> > > Sorry, can't do this
> > 
> > 
> > No worries. I'll leave this issue open if anyone wants to make a patch for it, but feel free to close it if you want.
> 
> I found a solution, try this
> 
> ```css
> .tabbrowser-tab {min-width: initial !important;}
> .tab-content {overflow: hidden !important;}
> ```

Doesn't work, it makes the tab impossible to close when they become smaller

**Comment by edelvarden** [comment]
> Doesn't work, it makes the tab impossible to close when they become smaller

To do this, use middle click on the tab.
