### ISSUE TITLE
[Feature Request]: 

### ISSUE THREAD

**Issue by Filip46820** [edelvarden/material-fox-updated#43]
### Description

Would it be possible to change the background of the navigation panel and possible behind search bar (not the actual search bar eg. the darker color)? Heres a provided screenshot. As for what I'm trying to do. Or a way for me to modify the code to make it work as currently it works only unfocused.
![obrazek](https://github.com/edelvarden/material-fox-updated/assets/144820919/babe3f63-7761-4d0e-b922-8b6de1cf1627)

### Additional info (Optional)

Firefox version: 
Operating system:

**Comment by edelvarden** [comment]
> ### Description
> Would it be possible to change the background of the navigation panel and possible behind search bar (not the actual search bar eg. the darker color)? Heres a provided screenshot. As for what I'm trying to do. Or a way for me to modify the code to make it work as currently it works only unfocused. ![obrazek](https://private-user-images.githubusercontent.com/144820919/315371502-babe3f63-7761-4d0e-b922-8b6de1cf1627.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTExMDk3MDEsIm5iZiI6MTcxMTEwOTQwMSwicGF0aCI6Ii8xNDQ4MjA5MTkvMzE1MzcxNTAyLWJhYmUzZjYzLTc3NjEtNGQwZS1iOTIyLThiNmRlMWNmMTYyNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyMlQxMjEwMDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NWNmNTlmZWQ3M2NhM2Q5ZWY5N2ZhNWM3YzhlNWJlYzg0YWNjMmRlMzFmMzZhMzIwN2ZiNzA0MjllMDhiMTk0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.DisedxhWKmTuj2Bsi77rB4X7dV1J5SQI9fJcihaRoJE)
> 
> ### Additional info (Optional)
> Firefox version: Operating system:

Experiment with `--mf-background-color-100` (for the nav bar background) and `--mf-background-color-50` (for the url bar background) in custom css.
