### ISSUE TITLE
[Bug]: The search bar is still rectangular, not round

### ISSUE THREAD

**Issue by quarkquartet** [edelvarden/material-fox-updated#44]
### What happened?

<img width="1003" alt="image" src="https://github.com/edelvarden/material-fox-updated/assets/26316540/64315301-e107-4bc4-98fa-0983513d8264">

I'm expecting a rounded search bar as in chrome, also as shown in the readme. But it's still rectangular. Is that a problem from my side?

### Steps to reproduce the problem

1. Download the latest version.
2. Copy to the profile folder.
3. Restart Firefox.

### Additional info (Optional)

Firefox version: 124.0.1
Operating system: MacOS 14

**Comment by edelvarden** [comment]
Yes, this problem from your side, I can't reproduce this issue. You can try adding this code to your custom css:

```css
.search-handoff-button {
 border-radius: 99px !important;
}
```

**Comment by quarkquartet** [comment]
> Yes, this problem from your side, I can't reproduce this issue. You can try adding this code to your custom css:
> 
> ```css
> .search-handoff-button {
>  border-radius: 99px !important;
> }
> ```

This code does not work for me, so it must be some issue happening. I completely reinstalled everything and it works now. Thank you.
