### ISSUE TITLE
[Feature Request]: Context Menu icons

### ISSUE THREAD

**Issue by vishnup95** [edelvarden/material-fox-updated#48]
### What happened?

All context menu icons are missing. 

![image](https://github.com/edelvarden/material-fox-updated/assets/50899727/3d33a45f-1ffa-41ae-880f-41df7d3c5bc6)

### Steps to reproduce the problem

1. Open a new tab
2. Right click to open context menu
3 ... profit(?)

### Additional info (Optional)

Firefox version: Dev Version - 126.0b9 (64-bit)
Operating system: Linux Desktop - Fedora 40

**Comment by edelvarden** [comment]
I did not added icons for the context menu, only for the general menu, maybe I'll add them later.

**Comment by edelvarden** [comment]
Implemented.
