### ISSUE TITLE
[Feature Request]: Select search engine

### ISSUE THREAD

**Issue by xllifi** [edelvarden/material-fox-updated#49]
### Description

In vanilla Firefox, you can select a search engine right under search suggestions. That is useful, a shame it's not present in this theme.
Sorry if I'm missing it or if there is a config option for that.

### Additional info (Optional)

Firefox version: 126.0
Operating system: Windows 11 `22631.3593`

**Comment by edelvarden** [comment]
Just start typing a search engine name, then select from suggestion

![image](https://github.com/edelvarden/material-fox-updated/assets/42596339/a7d351f0-1340-4725-a05a-e95a6884bc98)

As an alternative add the following user CSS rule, this is make the bottom panel visible again

```css
.search-one-offs {
  display: flex !important;
}
```

[How to add user CSS](https://github.com/edelvarden/material-fox-updated/tree/main?tab=readme-ov-file#custom-css-rules)
