### ISSUE TITLE
[Bug]: popup windows have a rounded corner and different color titlebar

### ISSUE THREAD

**Issue by NGSpace** [edelvarden/material-fox-updated#50]
### What happened?

on firefox:
![image](https://github.com/edelvarden/material-fox-updated/assets/71827944/3c37cf6c-5d99-4fff-8f90-458983193695)

on chrome:
![image](https://github.com/edelvarden/material-fox-updated/assets/71827944/1ac689b6-4b33-4615-97dc-217416414904)

### Steps to reproduce the problem

run `window.open("https://www.mozilla.org/", "mozillaWindow", "popup"); ` to test it.

### Additional info (Optional)

Firefox version: 126.0
Operating system: Windows 11

**Comment by AlvaroVazquezJr** [comment]
Also second this one, thank you for reporting!
