### ISSUE TITLE
[Bug]: Not loaded on Win 10 126.0 (64-bit)

### ISSUE THREAD

**Issue by quarkquartet** [edelvarden/material-fox-updated#51]
### What happened?

Just follow every steps of this installation, and restart firefox and nothing changes.

I tried to enter about:config and customize those new variables defined here and these variables do not exist.

So clearly my firefox is not loading the userChrome.

### Steps to reproduce the problem

Download the release.
Set those required variables to true.
Open about:support and open profile folder.
Copy the unzipped file into profile folder. I can clearly see the chrome folder is in the profile folder now.
Restart firefox, nothing happens.

### Additional info (Optional)

Firefox version:  126.0 (64-bit)
Operating system: Win10.

**Comment by edelvarden** [comment]
I Install clear Firefox 126 on Windows 10 64-bit, and variables are exist, only one variable don't exist `layout.css.color-mix.enabled`, but it can be added manually. 
Did you try to create these variables manually?
![image](https://github.com/edelvarden/material-fox-updated/assets/42596339/48fa5778-ee9f-41bb-bd71-38cedd5fb371)

**Comment by quarkquartet** [comment]
![image](https://github.com/edelvarden/material-fox-updated/assets/26316540/06785e45-b4b2-48bf-a12c-23dd45c2ab78)


new variables like userChromexxx are not defined. And as you can see nothing works here. Any hint to debug? (Mac user, not very familar with windows)

**Comment by edelvarden** [comment]
`userChrome.*` this is my own created variables, you need manually add them, to just enable this user CSS theme you need set `toolkit.legacyUserProfileCustomizations.stylesheets`, `svg.context-properties.content.enabled` and `layout.css.color-mix.enabled` to `true`.

Paste variable name and then click plus button
![image](https://github.com/edelvarden/material-fox-updated/assets/42596339/3f495883-a58b-4d12-8d3a-d4e721da9d89)

After that you can see your variable
![image](https://github.com/edelvarden/material-fox-updated/assets/42596339/99f1f760-263f-4e7a-b021-d91ef84348f5)

**Comment by quarkquartet** [comment]
> set toolkit.legacyUserProfileCustomizations.stylesheets, svg.context-properties.content.enabled and layout.css.color-mix.enabled to true.

I already did this at the very beginning.

**Comment by edelvarden** [comment]
If variables are true make sure the chrome folder is exist, this is all what you need

![image](https://github.com/edelvarden/material-fox-updated/assets/42596339/80007ae0-561c-4cbc-9826-fb8776b6a5bb)
![image](https://github.com/edelvarden/material-fox-updated/assets/42596339/d0d0880c-ee5a-47b5-93c5-b188a97a2714)

**Comment by quarkquartet** [comment]
![image](https://github.com/edelvarden/material-fox-updated/assets/26316540/1bd63077-77c6-4cdc-afe4-1eb6ea1a689d)
![image](https://github.com/edelvarden/material-fox-updated/assets/26316540/38d0da44-81e1-4ec7-8891-0a24741a4c12)
![image](https://github.com/edelvarden/material-fox-updated/assets/26316540/507573db-6bcc-4604-99cf-86215bbcb713)
![image](https://github.com/edelvarden/material-fox-updated/assets/26316540/55b2bb84-30db-413b-a4b1-27cd93d52531)

All are here...That's why I'm confused. I've been using this repo on my mac for a long time and this is the first time for me to set it up on a windows and what a big surprise for me. I really couldn't figure it out....

**Comment by edelvarden** [comment]
Extract archive from releases https://github.com/edelvarden/material-fox-updated/releases/latest instead of source code

**Comment by quarkquartet** [comment]
Ahhhh how stupid am I.....sorry for this silly post.

**Comment by VityaSchel** [comment]
I tried everything but it does not work on macos :(
firefox 128.0.3
1. downloaded release .zip
2. extracted directory to current profile directory (i tried putting whole chrome folder there and files of chrome in profile directory)
3. restarted firefox

**Comment by edelvarden** [comment]
@VityaSchel , can you provide any screenshots or the directory structure?

Firefox 128.0.3 and material fox v1.2.6, works fine. Ensure your paths is correct, please.
![image](https://github.com/user-attachments/assets/857f04bf-b451-4a9d-999a-b5f6ab6f09e8)

**Comment by edelvarden** [comment]
@VityaSchel , I think you forgot to set the preferences in `about:config` to `true`. Please read the [Getting Started](https://github.com/edelvarden/material-fox-updated?tab=readme-ov-file#-getting-started) section again.
