### ISSUE TITLE
[Feature Request]: "Search with" option below the search suggestions

### ISSUE THREAD

**Issue by carkks** [edelvarden/material-fox-updated#54]
### Description

This problem is similar to #49, for...
The problem wasn't described correctly, I think. Below the search suggestions, there is an option that allows us to choose a search engine. Both in the address bar and in the search bar. 
![image](https://github.com/edelvarden/material-fox-updated/assets/82451852/02f760aa-3d0b-4c3b-b6f6-842d1402ee12)
I had this problem trying to add a Mycroft site as a search engine, only I didn't see the option available.

### Additional info (Optional)

Firefox version: 126.1
Operating system: Windows 11

**Comment by edelvarden** [comment]
Did you try?

> As an alternative add the following user CSS rule, this is make the bottom panel visible again
> 
> ```css
> .search-one-offs {
>   display: flex !important;
> }
> ```
> 
> [How to add user CSS](https://github.com/edelvarden/material-fox-updated/tree/main?tab=readme-ov-file#custom-css-rules)
