### ISSUE TITLE
[Bug]: userChrome.theme-default doesn't apply the older userChrome.default-theme-colors settings

### ISSUE THREAD

**Issue by joshuataylor** [edelvarden/material-fox-updated#55]
### What happened?

Since commit [d8392e989f32d68abd517e05fe844af0bc909773](https://github.com/edelvarden/material-fox-updated/commit/d8392e989f32d68abd517e05fe844af0bc909773), I no longer see the "default colors" in Firefox Nightly `129.0a1 (2024-06-18) (64-bit)`, MacOS.

I've also set `userChrome.theme-default` to `true`, the slightly darker topbar was :100:, is there a way to return the old look?

Previously, it would look like this:
![material_fox_old](https://github.com/edelvarden/material-fox-updated/assets/225131/c3fdc76d-e25c-49fc-9a43-3e38dbefe8f3)

Now it looks like this (note the top bar shading change):
![material_fox_new](https://github.com/edelvarden/material-fox-updated/assets/225131/f6724c8a-4560-45af-975a-e9b78d49b038)

Would this now be handled via a custom CSS file, if so I could contribute that back :+1:

### Steps to reproduce the problem

1. Open Firefox
2. `about:config` -> `userChrome.theme-default` to `true`
3. Reload Firefox

### Additional info (Optional)

Firefox version: 
Operating system:

**Comment by edelvarden** [comment]
There is no need for a custom CSS file because I wrap all color rules in a media query. When `userChrome.theme-default` is `true`, these rules won't be loaded, and Firefox will use the default colors. I think the issue is with the title bar active/inactive color. I'll fix it later.

**Comment by joshuataylor** [comment]
Awesome, thanks! Been really loving this theme for quite a while :).

Thanks for maintaining it!

**Comment by edelvarden** [comment]
> Would this now be handled via a custom CSS file

As I checked, the latest version fully matches the native Firefox color scheme, so I won't override it. 
You can restore the old title bar color, as shown in your screenshot, by simply placing the following code in the `custom.css` file:

```css
@media (prefers-color-scheme: light) {
  :root:not(:-moz-window-inactive) #navigator-toolbox {
    background-color: #c7c9c9 !important;
    background-image: none !important;
  }

  :root:not(:-moz-window-inactive) #toolbar-menubar,
  :root:not(:-moz-window-inactive) #TabsToolbar,
  :root:not(:-moz-window-inactive) #titlebar {
    background-color: #c7c9c9 !important;
    background-image: none !important;
  }
}
``
