### ISSUE TITLE
Chrome Old UI

### ISSUE THREAD

**Issue by ArminEskandarii** [edelvarden/material-fox-updated#56]
### Description

Hi, Is Chrome OLD UI available here?
If not please add it.
By old i don't mean the very old ones, As you may know Chrome's UI have recently changed, And they force all users to use the new UI (They started rounding the context menu and stuff...), We were able to revert it back to the old UI by disabling side panel in chrome flags, But it doesn't work anymore.

Anyway I know this project is about Firefox but I would really appreciate it if you make that.

### Additional info (Optional)

Firefox version: 
Operating system: Windows

**Comment by edelvarden** [comment]
Supports both, using the old UI by default, the new UI is an option and is enabled via about:config preferences, this is described in the readme.

**Comment by hubertsng** [comment]
> Anyway I know this project is about Firefox but I would really appreciate it if you make that.

Are you asking for a css FOR Chrome or are you asking for an enhancement FOR Firefox to look like how you want Chrome to look? This project is for Firefox and would (should) not be compatible with Chrome and I don't think anyone's going to just make a Chrome one like that.

**Comment by ArminEskandarii** [comment]
> Supports both, using the old UI by default, the new UI is an option and is enabled via about:config preferences, this is described in the readme.

Alright then I installed the theme, How can I activate the old UI (the one before Chrome Refresh).

Update: I'm currently disabling a lot of settings in about:config as mentioned in readme. last thing i want to do it to make the context menu not rouned

**Comment by edelvarden** [comment]
Closed, because it's already implemented.
