### ISSUE TITLE
Weird black bar under tabs

### ISSUE THREAD

**Issue by Buco7854** [edelvarden/material-fox-updated#6]
I noticed this thin black bar under the tabs, here is a screenshot (I suppose its a border).
![firefox-chrome-theme-black-bar](https://user-images.githubusercontent.com/80671351/228661659-60919f4b-4e36-4e07-ac6f-294fe9009f88.png)

**Comment by edelvarden** [comment]
I fixed this, it was "Firefox view" tab margin.

**Comment by Buco7854** [comment]
thanks a lot👍
