### ISSUE TITLE
[Bug]: Bookmarks toolbar text is not aligned correctly

### ISSUE THREAD

**Issue by Crunchbits** [edelvarden/material-fox-updated#60]
### What happened?

Small visual inconsistency:
The bookmark toolbar text is a just a minuscule bit too high. Noticeable when compared to the icons.
![image](https://github.com/user-attachments/assets/cb4f71ca-cea5-4643-bc33-d267d7d93fbd)

### Steps to reproduce the problem

1. Show bookmarks toolbar with bookmarks

### Additional info (Optional)

Firefox version: 128.0
Operating system: Windows 10 (64-bit)

**Comment by Crunchbits** [comment]
Actually upon further investigation, this seems to be an "issue" with the Roboto font. The default font that Chrome uses on Windows 10 (Segoe UI) lines up perfectly.

I don't know if there is any theme philosophy in terms of what this project wants to accomplish. Such as a philosophy of it being as accurately similar to Chrome when possible. Or a philosophy of it being as overwhelmingly accurately similar to Chrome but with some design flexibility.
If it's the first then I would say to maybe change it so that the font depends on the OS's default system font(I believe that's how Chrome handles it). If it's the second or another philosophy then it could be kept the same. Either ways this is a wonderful project!

**Comment by edelvarden** [comment]
Roboto is used only for Windows, but you can replace the font using `custom.css`. I replaced the Segoe font because as for me it looks too thin with the poor render, and Roboto more corresponds to the material design UI's.
