### ISSUE TITLE
[Feature Request]: Add top padding to maximized window

### ISSUE THREAD

**Issue by Crunchbits** [edelvarden/material-fox-updated#61]
### Description

Make more consistent with how Chrome appears by adding a few pixels(I counted ~6 pixels on Chrome) of padding to the top of the browser window. On top of being more consistent with Chrome, it also accentuates the fact that tabs are rounded.

Firefox:
![image](https://github.com/user-attachments/assets/192324a4-bd42-48c1-91f3-6bdb19134f59)

Chrome:
![image](https://github.com/user-attachments/assets/20eb967f-244e-4bf5-a876-7ca356281080)

### Additional info (Optional)

Firefox version: 128.0
Operating system: Windows 10 (64-bit)

**Comment by edelvarden** [comment]
There are no indentations in the old UI, you should enable `userChrome.ui-chrome-refresh` if you want this.

**Comment by Crunchbits** [comment]
Ah okay thank you for pointing me to this.
