### ISSUE TITLE
[Bug]: Highlight around current tab

### ISSUE THREAD

**Issue by MulesGaming** [edelvarden/material-fox-updated#62]
### What happened?

There is a purple highlight around the current tab.
![image](https://github.com/user-attachments/assets/48b9a492-4de3-4c99-9f50-725962dedd2a)

### Steps to reproduce the problem

1. Open Firefox
2. Look at the new tab

### Additional info (Optional)

Firefox version: 129.0b5 
Operating system: OpenSuse Tumbleweed

**Comment by edelvarden** [comment]
Did you use any theme?

**Comment by MulesGaming** [comment]
I tested it with the default theme and Dracula theme and it happened on both.

**Comment by dorkbuttt** [comment]
im getting the same issue but this time it's black. running latest 1.2.5 and on firefox nightly 130.0a1 2024-07-27

<img width="595" alt="Screenshot 2024-07-27 at 1 59 14 PM" src="https://github.com/user-attachments/assets/b95c50da-0cc1-4751-9bdb-c97d1976c77f">


edit: confirmed it works on stable firefox 128.0.3

**Comment by edelvarden** [comment]
@dorkbuttt, I can't reproduce this issue. Are you familiar with custom.css? If so, could you add the following code and let me know if it helps:

```css
:root,
html,
body,
.tab-background{
    --tab-selected-outline-color: transparent !important;
  }
```

**Comment by dorkbuttt** [comment]
It did fix the outline issue, but now there's a weird seam that doesn't make the tab blend in with the rest of the UI.

<img width="595" alt="Screenshot 2024-07-27 at 2 12 39 PM" src="https://github.com/user-attachments/assets/e220bda9-869d-4cb4-98d5-5a7f55a9e27d">

**Comment by edelvarden** [comment]
@dorkbuttt, is this on the nighty or stable?

**Comment by dorkbuttt** [comment]
@edelvarden nightly

edit: to clarify, this issue is not present in stable.
