### ISSUE TITLE
[Bug]: CSS variable doesn't change title bar color in "System theme - auto" mode

### ISSUE THREAD

**Issue by zkisaboss** [edelvarden/material-fox-updated#67]
### Description

The tab and address bar colors don't match chrome.

### Additional info (Optional)

Firefox Version: 129.0.1
MacOS Version: 14.6.1 (23G93)

**Comment by zkisaboss** [comment]
<img width="1680" alt="Screenshot 2024-08-19 at 2 43 05 PM" src="https://github.com/user-attachments/assets/17a8591f-962b-4f4a-9ee4-292ef6a25297">

**Comment by zkisaboss** [comment]
If anyone has the custom CSS for chrome's color scheme can u send it to me

**Comment by edelvarden** [comment]
@zkisaboss, already implemented, [`userChrome.theme-chrome-refresh`](https://github.com/edelvarden/material-fox-updated?tab=readme-ov-file#available-preferences)

**Comment by zkisaboss** [comment]
I had the theme refresh enabled but my colors aren't matching chrome. New bookmark colors and hover colors are spot on but the greys don't match chrome's theme.

**Comment by zkisaboss** [comment]
I'm an idiot lol, thanks for maintiaining materialfox so well

**Comment by zkisaboss** [comment]
`--md-background-color-0` not displaying `#1f2020` but rather `#1c1b22`.
All three preferences are true.
userChrome.ui-chrome-refresh and userChrome.theme-chrome-refresh are true.

I even added the following to my custom.css file, and the dark tones are still the wrong color.
```
:root,
html,
body {
  --md-background-color-0: #1F2020 !important;
}
```

**Comment by edelvarden** [comment]
@zkisaboss , I can’t reproduce your issue. I tested it with red color, and I can change the color:

![image](https://github.com/user-attachments/assets/af95c376-b04c-4b91-b42a-19fde216f67d)

**Comment by zkisaboss** [comment]
![](https://i.gyazo.com/f6594e0295591d95ee81767663681660.png)

When I try to reproduce

**Comment by zkisaboss** [comment]
I think it's a problem with userChrome.theme-chrome-refresh

**Comment by zkisaboss** [comment]
I fixed the issue by manually selecting the dark mode (or light mode) theme, as Firefox's "System theme - auto" setting is not detected in user-chrome.css.

You might want to update the readme or modify the user-chrome.css file

**Comment by edelvarden** [comment]
@zkisaboss, thanks for the additional info. Yes, the variable doesn’t work with "System theme - auto" mode. I’ll see what can be done.
