### ISSUE TITLE
[Bug]: Github theme URL highlight not visible

### ISSUE THREAD

**Issue by adriansticoid** [edelvarden/material-fox-updated#70]
### What happened?

So this is how it looks like when a URL is highlighted with the Chrome refresh theme:
![image](https://github.com/user-attachments/assets/afbae8af-23c2-4d16-bd98-0814a689151c)

And this is how it looks like with the Github theme:
![image](https://github.com/user-attachments/assets/1d1e5d6a-95b9-4239-a0ab-3438909d0c92)

I swear that's highlighted but it's not visible. This is the only issue I found so far. Really love the theme and thanks for your work.

### Steps to reproduce

1. Activate Github theme
2. Try to highlight a URL

**Comment by AzuredBlue** [comment]
Noticed the same, color-mix() expects a percentage, but its using a number
Until its fixed, a fix is to change the `0.4` in `--md-selection-background-color` (where you added the theme) to `40%`

**Comment by adriansticoid** [comment]
@AzuredBlue Hi, from
--md-selection-background-color: color-mix(
      in srgb,
      transparent 0.4,

I changed it to
--md-selection-background-color: color-mix(
      in srgb,
      transparent 40%,

and the issue persist. Did I do it incorrectly?

**Comment by AzuredBlue** [comment]
> @AzuredBlue Hi, from --md-selection-background-color: color-mix( in srgb, transparent 0.4,
> 
> I changed it to --md-selection-background-color: color-mix( in srgb, transparent 40%,
> 
> and the issue persist. Did I do it incorrectly?

Hm, I have it set to
```
      --md-selection-background-color: color-mix(
        in srgb,
        transparent 40%,
        #388bfd
      );
```
and it works

Make sure it's the correct file, that its saved, and that you have restarted Firefox. 
If it still doesnt work then you could just remove the transparency and make it a single color by setting it to
`--md-selection-background-color: #388bfd;`
or simply remove it, so it will use Firefox's default selection background color

Either way it shouldnt take too long for a fix

**Comment by adriansticoid** [comment]
@AzuredBlue yep smooth brain moment. I was indeed trying to edit the wrong file. It looks correct and prettier now. Thank you so much!

**Comment by adriansticoid** [comment]
@AzuredBlue I found another one
When hovering through suggested tabs, the highlight is not visible

Normal:
![image](https://github.com/user-attachments/assets/6a58abca-586d-43d3-8aa2-29bbf1ad4064)

Github theme:
![image](https://github.com/user-attachments/assets/ef6668fe-0454-420c-a25e-acb8a7525a5c)

**Comment by AzuredBlue** [comment]
> @AzuredBlue I found another one When hovering through suggested tabs, the highlight is not visible
> 
> Normal: ![image](https://private-user-images.githubusercontent.com/122187236/361070187-6a58abca-586d-43d3-8aa2-29bbf1ad4064.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ0ODM2NDAsIm5iZiI6MTcyNDQ4MzM0MCwicGF0aCI6Ii8xMjIxODcyMzYvMzYxMDcwMTg3LTZhNThhYmNhLTU4NmQtNDNkMy04YWEyLTI5YmJmMWFkNDA2NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyNFQwNzA5MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMjRmMTdkZDc1YjkzNzFjNWQzMTIyZWRmY2Y4YjQyMzhiOTNhYjQ0MjBhMjczMDFiMjM1MGY5OGE4ZTU4Mzg5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.uHd_l1MKuq5B07Xu_lV0yt3NQICCILswWbhCRnLFBIY)
> 
> Github theme: ![image](https://private-user-images.githubusercontent.com/122187236/361070260-ef6668fe-0454-420c-a25e-acb8a7525a5c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ0ODM2NDAsIm5iZiI6MTcyNDQ4MzM0MCwicGF0aCI6Ii8xMjIxODcyMzYvMzYxMDcwMjYwLWVmNjY2OGZlLTA0NTQtNDIwYy1hMjVlLWFjYjhhNzUyNWE1Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyNFQwNzA5MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMzkxODk2MDBkZjdlZjhjYTZjZGMwOTM1MWM1ZmU1N2NjNzExMTg4MWIxNjMyMGE0MjgzMGRjN2IzYWE1MGE3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.YNP1p6zXHQOdT9gl3SwtShL5FM6YOhDRxOp3nQjuvY8)

Seems to be because `--md-background-color-50` and `--md-menu-background-color-hover` share the same color. You can simply change the latter to a lighter color. I used [this](https://mdigi.tools/lighten-color/#161b22) with 10% (#28313e) and it looks like this:

![image](https://github.com/user-attachments/assets/6868cf44-24fe-4a6a-9f16-4b52297a9d94)
Not sure if that will cause issues with anything else. I'll leave it to the repo owner to choose a better color if it does

**Comment by adriansticoid** [comment]
@AzuredBlue I copied what you did and yes it looks better now. Thank you. Will keep an eye out for more issues like this.
