### ISSUE TITLE
Donate

### ISSUE THREAD

**Issue by zkisaboss** [edelvarden/material-fox-updated#72]
I'm having trouble donating with Ko-fi.com from my country. Do you accept any other payment methods?

**Comment by edelvarden** [comment]
@zkisaboss 
Thank you for your interest in supporting me. I’m not entirely sure, as I also face some limitations on most other platforms for my country, but I think you can use PayPal directly by visiting [https://www.paypal.com/myaccount/transfer/homepage/send](https://www.paypal.com/myaccount/transfer/homepage/send) and using my email:

`edelvarden@gmail.com`

**Comment by zkisaboss** [comment]
Thanks, let me know if you got it!

**Comment by edelvarden** [comment]
> Thanks, let me know if you got it!

Thank you so much for the support, I got it.
