### ISSUE TITLE
[BUG] Vertical Line Appears on Tab Bar When Multiple Tabs Are Open

### ISSUE THREAD

**Issue by ghost** [edelvarden/material-fox-updated#75]
### What happened?

In Firefox version 130.0.1 (also in 131), there is a visual bug. When multiple tabs are open and the user is currently focused on the last tab, a vertical line appears on the left side of the tab bar. This line sometimes appears in the foreground, while at other times it remains in the background.

![obrázok](https://github.com/user-attachments/assets/b597d8bc-180a-4b70-ab4f-5d872c7863c8)

![obrázok](https://github.com/user-attachments/assets/fdc38362-1c72-400a-a1cf-7e74fba57fcb)

### Steps to reproduce

1. Open lots of tabs
2. Scroll to the end or open last tab
3. The line appears on the left

**Comment by kbc8090** [comment]
Yeah i tried for awhile to fix that and couldnt figure it out, it's only specific to the chrome-refresh option.  The line is fine but I couldnt get the content behind to line up behind it, think it could be z-index related but I tried all kind of margin/padding things to fix to no avail.

**Comment by edelvarden** [comment]
This issue will be fixed in future Firefox releases. I don't see this issue in versions 132 (Dev) and 133 (Nightly).

**Comment by zkisaboss** [comment]
@crucinal1 What screenshot tool do you use to blur the url's?

**Comment by ghost** [comment]
> @crucinal1 What screenshot tool do you use to blur the url's?

Greenshot
