### ISSUE TITLE
[Feature Request]: Make Roboto font as a separate option

### ISSUE THREAD

**Issue by dreamsynth** [edelvarden/material-fox-updated#77]
### Description

Using this theme, I would not want it to change the system fonts of the browser. If you fix it via CSS, according to the instructions in the README, then for some reason it affects the websites by changing the font on them too, so I think it makes sense to make the font change on Roboto a separate option and not enable it by default.

**Comment by edelvarden** [comment]
Implemented as `userChrome.ui-system-font` preference, set it to `true` to use the default system font instead of Roboto.
