### ISSUE TITLE
[Bug]: Tabs spacing is wrong on nightly 134.0a1 (2024-11-09)

### ISSUE THREAD

**Issue by joshuataylor** [edelvarden/material-fox-updated#84]
### What happened?

<img width="891" alt="image" src="https://github.com/user-attachments/assets/5e2e2788-f8b5-49d5-b2e3-15eb44d30154">

Version: `134.0a1 (2024-11-09) (aarch64)`

### Steps to reproduce

1. Update to nightly 2024-11-09
2. See tabs being spaced weirdly

### Additional info (Optional)

Version: `134.0a1 (2024-11-09) (aarch64)`
MacOS 15.1 (24B83)

**Comment by keatit71** [comment]
having the same issue on windows 11 latest firefox nightly 134.0a1 (2024-11-09) (64-bit
![image](https://github.com/user-attachments/assets/33f5a1e1-f2b0-46f0-a839-aae69033eb0d)

**Comment by drequeary** [comment]
A quick fix is to add `--tabstrip-min-height: 0 !important` to your custom css. That worked for me.

**Comment by ezeraiser** [comment]
> A quick fix is to add `--tabstrip-min-height: 0 !important` to your custom css. That worked for me.

Yeah it's worked for me too.

**Comment by SuperKenCoder** [comment]
I don't have a custom css to add this to. This has happened after installing it for the first time.

**Comment by Kennxn** [comment]
Thank you, this has worked.
