### ISSUE TITLE
[Bug]: Tabs floating over the toolbar

### ISSUE THREAD

**Issue by AlvaroVazquezJr** [edelvarden/material-fox-updated#88]
### What happened?

The new Firefox update (133.0) added a visual bug that causes Firefox tabs to float above the toolbar.

![image](https://github.com/user-attachments/assets/508ae361-c991-4605-9d13-9ae680190abf)

### Steps to reproduce

1. Open Firefox
2. Observe the tabs

### Additional info (Optional)

Firefox version: 133.0
Operating system: Windows 11

**Comment by edelvarden** [comment]
Duplicate of #84

**Comment by Kennxn** [comment]
Just had the same issue. I fixed it by going into the chrome folder, going to custom_example, opening it and putting in "--tabstrip-min-height: 0 !important" and then renaming the folder to "custom"

**Comment by AlvaroVazquezJr** [comment]
Apologies for the duplicate, and thank you @SuperKenCoder that worked for me!
