### ISSUE TITLE
[Bug]: Buggy tabs after update to Firefox 133.0

### ISSUE THREAD

**Issue by ghost** [edelvarden/material-fox-updated#89]
### What happened?

The mouse was placed on the 'What's New...' tab, and then something below the tab appeared, like a preview window.
Anyway, the entire tab bar is broken; things are not centered.

I have browser.tabs.hoverPreview.enabled set to FALSE.

![2024-11-27 15_16_43-Issues · edelvarden_material-fox-updated — Mozilla Firefox](https://github.com/user-attachments/assets/4a6f62ec-ce5a-4fcd-8c1e-06f4d7e057ad)

### Steps to reproduce

Not necessary

### Additional info (Optional)

Firefox: 133.0

**Comment by lubelski** [comment]
dupe with https://github.com/edelvarden/material-fox-updated/issues/90

**Comment by ghost** [comment]
He brought up the same topic only after me, so this appears to be a duplicate. Can be closed.
