### ISSUE TITLE
[Bug]:  'Find in Page' text box which appears after pressing Ctrl+F doesn't show any text when something is typed.

### ISSUE THREAD

**Issue by kama-vats** [edelvarden/material-fox-updated#9]
### Description

**Below Image shows 'Find in Page' text box without any text and selection. It shows bugged arrow placement and two weirdly placed lines in the middle.**
![image](https://user-images.githubusercontent.com/108620749/234661889-375612fe-dbb1-4279-ac83-74ff2e5346a9.png)

**Following image shows 'Find in Page' text box with text and selection. Text is not visble/too much too the left and box selection highlighting are not present.**
![image](https://user-images.githubusercontent.com/108620749/234663094-edd343dd-f71c-42ac-bafb-bdc9c2ff881b.png)

**Expected behavior (Chromium)**
![image](https://user-images.githubusercontent.com/108620749/234664924-33040ebe-be81-4f95-b8fd-6efbf8796a97.png)

### Additional info

Arch Linux 6.2.12
Librewolf version 112.0.1-2 (64-bit)

**Comment by edelvarden** [comment]
Firefox find bar don't support auto width as in old versions, but I applied general fixes.
