### ISSUE TITLE
[Bug]: There is some weird amount of space under the tabs.

### ISSUE THREAD

**Issue by Zap-09** [edelvarden/material-fox-updated#90]
### What happened?

<img width="645" alt="Screenshot 2024-11-27 224607" src="https://github.com/user-attachments/assets/63e620f2-bf44-49c7-b186-964d037c8639">

There is some weird amount of space under the tabs.
Also the new tab icon looks weird as well, So was I was wandering if you can change these two?

### Steps to reproduce

No steps required

### Additional info (Optional)

FireFox version 133.0 (64-bit)

OS Windows 10 pro

**Comment by kbc8090** [comment]
Others have reported same thing, add:

`
#tabbrowser-tabs {
  min-height: unset !important;
}
`

**Comment by adriansticoid** [comment]
> Others have reported same thing, add:
> 
> `#tabbrowser-tabs { min-height: unset !important; }`

Can confirm this fixes it after adding to custom.css

**Comment by lubelski** [comment]
I'm on a mac.  I created (renamed the example file) the file: 

`/Library/Application Support/Firefox/Profiles/{profile}/custom.css`

and then added the line mentioned above.  

![CleanShot 2024-11-27 at 20 14 21@2x](https://github.com/user-attachments/assets/43845a60-6125-4494-a7c3-45fa775eeea4)

Is anything more than a restart of firefox needed to apply this change? 

I'm still seeing the gap under the tabs

**Comment by Zap-09** [comment]
Ok I am writing this for the people who are not good with stuff like this(like me).

Type `about:support` in the URL bar.

Scroll down to the `Profile Folder `section and find `Root Directory` click `Open Folder`.

Look for `Chrome` folder. There will be a file named `custom_example.css` make a copy of it and rename it to `custom.css`.

Open that file and copy and paste this

```
:root,
html,
body {
    /* add your css variables below */
    
}
#tabbrowser-tabs { min-height: unset !important; }
/* add your user css below */


```
And you are done close and re-open FireFox this should fix it.
