### ISSUE TITLE
[Bug]: Gap between address bar and tabs

### ISSUE THREAD

**Issue by JuHyeong3401** [edelvarden/material-fox-updated#91]
### What happened?

There is a gap between tabs and address bar after firefox update 133
![스크린샷 2024-11-28 23 22 23](https://github.com/user-attachments/assets/4f6a4e96-32c6-4609-acca-b43d6e6a1767)

### Steps to reproduce

When I opened firefox after updated version 133, there was gap between tabs and address bar.

### Additional info (Optional)

Firefox version : 133.0, Operating system : Mac os Sequoia

**Comment by TapdigSoltanov** [comment]
Redownloading the files and putting them back in the Chrome directory fixed it.

**Comment by quarkquartet** [comment]
Same issue here. I even remove the chrome folder and use the vanilla Firefox, and the gap is still there. It seems the new version of firefox did something there.
