### ISSUE TITLE
[Bug]: Latest update (133.0) broke tabs

### ISSUE THREAD

**Issue by Amcro** [edelvarden/material-fox-updated#92]
### What happened?

![image](https://github.com/user-attachments/assets/8c680a28-7dcd-4f41-a86c-e0172f7c6a50)

Latest update of Firefox (133.0) broke the theme, there is now space between tabs and address bar.

### Steps to reproduce

1. Update to 133.0
2. Restart browser

### Additional info (Optional)

Firefox version: 133.0 (64 bit)
OS: Windows 11 24H2

**Comment by RogerioTDS** [comment]
Same problem on Arch Linux

**Comment by edelvarden** [comment]
Fixed in #84. Reinstall zip please.
