### ISSUE TITLE
[Feature Request]: Adding custom background images.

### ISSUE THREAD

**Issue by Zap-09** [edelvarden/material-fox-updated#93]
### Description

![image](https://github.com/user-attachments/assets/cec2bbb2-7f38-4ca9-b67f-d6253ab86987)

So I was wandering is there a way to add custom background image?

### Additional info (Optional)

FireFox version 133.0 (64bit)
OS Windows 10pro

**Comment by AlvaroVazquezJr** [comment]
@Zap-09, you can accomplish this using a userContent.css file in your Chrome folder and inputting the following:

```
@import "user-content.css";
@import "theme-material-blue.css";
@import "custom.css";

@-moz-document url-prefix(about:home), url-prefix(about:newtab) { .click-target-container *, .top-sites-list * { color: #fff !important ; text-shadow: 2px 2px 2px #000 !important ; }

body { background: url(wallpaper.jpg) !important ; background-size: cover !important ; } }
```

Then just add your desired wallpaper image into the Chrome folder and name it "wallpaper.jpg".

**Comment by Zap-09** [comment]
@AlvaroVazquezJr Thank you it worked. I guess I will close this issue then.
